name: widgetbook_workspace
description: "Homework widget book"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.14.3
  widgetbook_annotation: ^3.5.0
  flutter_lab:
    path: ../
  get_it: ^8.1.0
  talker_flutter: ^4.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.13.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: SilpoText
      fonts:
        - asset: assets/fonts/SilpoText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SilpoText-Regular.ttf
          weight: 400
